"""type_model

Revision ID: 04c859eccdb6
Revises: cd3a0a28573f
Create Date: 2023-09-28 09:41:08.995015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c859eccdb6'
down_revision = 'cd3a0a28573f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('typing',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('from_id', sa.Integer(), nullable=False),
    sa.Column('to_id', sa.Integer(), nullable=False),
    sa.Column('typing', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('type_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('typing')
    # ### end Alembic commands ###
