"""Check live status

Revision ID: 907b89cc9186
Revises: 94bd45cde493
Create Date: 2023-10-21 15:43:13.581074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '907b89cc9186'
down_revision = '94bd45cde493'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'from_delete')
    op.drop_column('messages', 'to_delete')
    op.add_column('users', sa.Column('alive', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'alive')
    op.add_column('messages', sa.Column('to_delete', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('from_delete', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
