"""media

Revision ID: 94bd45cde493
Revises: 5a5a72a07f0d
Create Date: 2023-10-16 15:26:14.180007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94bd45cde493'
down_revision = '5a5a72a07f0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('media_from_id_fkey', 'media', type_='foreignkey')
    op.drop_constraint('media_to_id_fkey', 'media', type_='foreignkey')
    op.drop_column('media', 'to_id')
    op.drop_column('media', 'from_id')
    op.add_column('messages', sa.Column('is_media', sa.Boolean(), server_default='false', nullable=False))
    op.drop_column('messages', 'sent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sent', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_column('messages', 'is_media')
    op.add_column('media', sa.Column('from_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('media', sa.Column('to_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('media_to_id_fkey', 'media', 'users', ['to_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key('media_from_id_fkey', 'media', 'users', ['from_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
