"""profile

Revision ID: a615d8d400dd
Revises: 907b89cc9186
Create Date: 2023-10-22 18:50:42.341953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a615d8d400dd'
down_revision = '907b89cc9186'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile')
    # ### end Alembic commands ###
