"""initial

Revision ID: cd3a0a28573f
Revises: 
Create Date: 2023-09-25 17:12:00.480765

"""
from alembic import op
import sqlalchemy as sa
from Models import model


# revision identifiers, used by Alembic.
revision = 'cd3a0a28573f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone_no', sa.BigInteger(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('messages',
    sa.Column('msg_id', sa.Integer(), nullable=False),
    sa.Column('from_id', sa.Integer(), nullable=False),
    sa.Column('to_id', sa.Integer(), nullable=False),
    sa.Column('message', model.PGPString(), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sent', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('msg_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('users')
    # ### end Alembic commands ###
