"""pin_msg

Revision ID: fdc0c74ac4c4
Revises: a615d8d400dd
Create Date: 2023-10-31 15:47:25.649092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdc0c74ac4c4'
down_revision = 'a615d8d400dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media')
    op.add_column('messages', sa.Column('pin', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen')
    op.drop_column('messages', 'pin')
    op.create_table('media',
    sa.Column('media_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('media_loc', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('media_id', name='media_pkey')
    )
    # ### end Alembic commands ###
