export const url = 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Telegram-Animated-Emojis/main'
export const emojis = {
    Smileys: [
        'Alien Monster.webp', 'Face With Rolling Eyes.webp', 'Pouting Face.webp',
        'Alien.webp', 'Face With Spiral Eyes.webp', 'Relieved Face.webp',
        'Angry Face.webp', 'Face With Steam From Nose.webp', 'Robot.webp',
        'Angry Face With Horns.webp', 'Face With Symbols On Mouth.webp', 'Rolling On The Floor Laughing.webp',
        'Anguished Face.webp', 'Face With Tears Of Joy.webp', 'Sad But Relieved Face.webp',
        'Anxious Face With Sweat.webp', 'Face With Thermometer.webp', 'Saluting Face.webp',
        'Astonished Face.webp', 'Face With Tongue.webp', 'See No Evil Monkey.webp',
        'Beaming Face With Smiling Eyes.webp', 'Fearful Face.webp', 'Shushing Face.webp',
        'Cat With Tears Of Joy.webp', 'Flushed Face.webp', 'Skull And Crossbones.webp',
        'Cat With Wry Smile.webp', 'Frowning Face.webp', 'Skull.webp',
        'Clown Face.webp', 'Frowning Face With Open Mouth.webp', 'Sleeping Face.webp',
        'Cold Face.webp', 'Ghost.webp', 'Sleepy Face.webp',
        'Confounded Face.webp', 'Goblin.webp', 'Slightly Frowning Face.webp',
        'Confused Face.webp', 'Grimacing Face.webp', 'Slightly Smiling Face.webp',
        'Cowboy Hat Face.webp', 'Grinning Cat.webp', 'Smiling Cat With Heart Eyes.webp',
        'Crying Cat.webp', 'Grinning Cat With Smiling Eyes.webp', 'Smiling Face.webp',
        'Crying Face.webp', 'Grinning Face.webp', 'Smiling Face With Halo.webp',
        'Disappointed Face.webp', 'Grinning Face With Big Eyes.webp', 'Smiling Face With Hearts.webp',
        'Disguised Face.webp', 'Grinning Face With Smiling Eyes.webp', 'Smiling Face With Horns.webp',
        'Dizzy Face.webp', 'Grinning Face With Sweat.webp', 'Smiling Face With Smiling Eyes.webp',
        'Dotted Line Face.webp', 'Grinning Squinting Face.webp', 'Smiling Face With Sunglasses.webp',
        'Downcast Face With Sweat.webp', 'Hear No Evil Monkey.webp', 'Smiling Face With Tear.webp',
        'Drooling Face.webp', 'Hot Face.webp', 'Smirking Face.webp',
        'Exploding Head.webp', 'Hugging Face.webp', 'Sneezing Face.webp',
        'Expressionless Face.webp', 'Hushed Face.webp', 'Speak No Evil Monkey.webp',
        'Face Blowing A Kiss.webp', 'Kissing Cat.webp', 'Squinting Face With Tongue.webp',
        'Face Exhaling.webp', 'Kissing Face.webp', 'Star Struck.webp',
        'Face Holding Back Tears.webp', 'Kissing Face With Closed Eyes.webp', 'Thinking Face.webp',
        'Face In Clouds.webp', 'Loudly Crying Face.webp', 'Tired Face.webp',
        'Face Savoring Food.webp', 'Lying Face.webp', 'Unamused Face.webp',
        'Face Screaming In Fear.webp', 'Melting Face.webp', 'Upside Down Face.webp',
        'Face Vomiting.webp', 'Money Mouth Face.webp', 'Weary Cat.webp',
        'Face With Diagonal Mouth.webp', 'Nauseated Face.webp', 'Weary Face.webp',
        'Face With Hand Over Mouth.webp', 'Nerd Face.webp', 'Winking Face.webp',
        'Face With Head Bandage.webp', 'Neutral Face.webp', 'Winking Face With Tongue.webp',
        'Face With Medical Mask.webp', 'Ogre.webp', 'Woozy Face.webp',
        'Face With Monocle.webp', 'Partying Face.webp', 'Worried Face.webp',
        'Face With Open Eyes And Hand Over Mouth.webp', 'Pensive Face.webp', 'Yawning Face.webp',
        'Face With Open Mouth.webp', 'Persevering Face.webp', 'Zany Face.webp',
        'Face Without Mouth.webp', 'Pile Of Poo.webp', 'Zipper Mouth Face.webp',
        'Face With Peeking Eye.webp', 'Pleading Face.webp',
        'Face With Raised Eyebrow.webp', 'Pouting Cat.webp',
    ],
    Activity: [
        '1st Place Medal.webp', 'Crystal Ball.webp', 'Soccer Ball.webp',
        '2nd Place Medal.webp', 'Firecracker.webp', 'Sparkler.webp',
        '3rd Place Medal.webp', 'Fireworks.webp', 'Sparkles.webp',
        'Admission Tickets.webp', 'Jack O Lantern.webp', 'Sports Medal.webp',
        'Artist Palette.webp', 'Magic Wand.webp', 'Ticket.webp',
        'Balloon.webp', 'Military Medal.webp', 'Trophy.webp',
        'Basketball.webp', 'Mirror Ball.webp', 'Video Game.webp',
        'Christmas Tree.webp', 'Party Popper.webp',
        'Confetti Ball.webp', 'Performing Arts.webp'
    ],
    'Food and Drink': [
        'Baby Bottle.webp', 'Hot Dog.webp',
        'Banana.webp', 'Lollipop.webp',
        'Bento Box.webp', 'Mate.webp',
        'Beverage Box.webp', 'Meat On Bone.webp',
        'Birthday Cake.webp', 'Oden.webp',
        'Bottle With Popping Cork.webp', 'Pancakes.webp',
        'Bubble Tea.webp', 'Pie.webp',
        'Canned Food.webp', 'Pizza.webp',
        'Chocolate Bar.webp', 'Popcorn.webp',
        'Clinking Glasses.webp', 'Poultry Leg.webp',
        'Cocktail Glass.webp', 'Pouring Liquid.webp',
        'Cookie.webp', 'Pretzel.webp',
        'Cooking.webp', 'Rice Ball.webp',
        'Cupcake.webp', 'Rice Cracker.webp',
        'Cup With Straw.webp', 'Sandwich.webp',
        'Custard.webp', 'Shortcake.webp',
        'Dango.webp', 'Soft Ice Cream.webp',
        'Doughnut.webp', 'Strawberry.webp',
        'Fish Cake With Swirl.webp', 'Stuffed Flatbread.webp',
        'Fork And Knife With Plate.webp', 'Sushi.webp',
        'French Fries.webp', 'Taco.webp',
        'Glass Of Milk.webp', 'Tropical Drink.webp',
        'Hamburger.webp', 'Tumbler Glass.webp',
        'Hot Beverage.webp', 'Wine Glass.webp',
    ],
    People: [
        'Baby.webp', 'Mx Claus.webp', 'Backhand Index Pointing Down.webp', 'Nail Polish.webp',
        'Backhand Index Pointing Left.webp', 'Nose.webp',
        'Backhand Index Pointing Right.webp', 'Ok Hand.webp',
        'Backhand Index Pointing Up.webp', 'Old Woman.webp',
        'Biting Lip.webp', 'Oncoming Fist.webp',
        'Bone.webp', 'Open Hands.webp',
        'Bust In Silhouette.webp', 'Palm Down Hand.webp',
        'Busts In Silhouette.webp', 'Palms Up Together.webp',
        'Call Me Hand.webp', 'Palm Up Hand.webp',
        'Clapping Hands.webp', 'People Hugging.webp',
        'Crossed Fingers.webp', 'Person Facepalming.webp',
        'Ear.webp', 'Person Shrugging.webp',
        'Ear With Hearing Aid.webp', 'Pinched Fingers.webp',
        'Eyes.webp', 'Pinching Hand.webp',
        'Family Man Woman Girl Boy.webp', 'Pregnant Woman.webp',
        'Folded Hands.webp', 'Raised Fist.webp',
        'Footprints.webp', 'Raised Hand.webp',
        'Foot.webp', 'Raising Hands.webp',
        'Handshake.webp', 'Right Facing Fist.webp',
        'Hand With Fingers Splayed.webp', 'Rightwards Hand.webp',
        'Hand With Index Finger And Thumb Crossed.webp', 'Santa Claus.webp',
        'Heart Hands.webp', 'Sign Of The Horns.webp',
        'Index Pointing At The Viewer.webp', 'Speaking Head.webp',
        'Index Pointing Up.webp', 'Technologist.webp',
        'Left Facing Fist.webp', 'Thumbs Down.webp',
        'Leftwards Hand.webp', 'Thumbs Up.webp',
        'Leg.webp', 'Tongue.webp',
        'Love You Gesture.webp', 'Tooth.webp',
        'Man Dancing.webp', 'Vampire.webp',
        'Man Facepalming.webp', 'Victory Hand.webp',
        'Man Health Worker.webp', 'Vulcan Salute.webp', 'Man Police Officer.webp', 'Waving Hand.webp',
        'Man Shrugging.webp', 'Woman Dancing.webp', 'Man Teacher.webp', 'Woman Facepalming.webp',
        'Man Technologist.webp', 'Woman Health Worker.webp',
        'Man Vampire.webp', 'Woman Police Officer.webp',
        'Man Zombie.webp', 'Woman Shrugging.webp',
        'Mechanical Arm.webp', 'Woman Technologist.webp',
        'Mechanical Leg.webp', 'Woman Vampire.webp',
        'Middle Finger.webp', 'Woman Zombie.webp',
        'Mouth.webp', 'Writing Hand.webp',
        'Mrs Claus.webp', 'Zombie.webp'
    ],
    Symbols: [
        'Anger Symbol.webp', 'Left Luggage.webp',
        'Aquarius.webp', 'Leo.webp',
        'Aries.webp', 'Libra.webp',
        'Baby Symbol.webp', 'Love Letter.webp',
        'Baggage Claim.webp', 'Mending Heart.webp',
        'Beating Heart.webp', 'Mens Room.webp',
        'Black Heart.webp', 'New Button.webp',
        'Blue Heart.webp', 'No One Under Eighteen.webp',
        'Broken Heart.webp', 'Ok Button.webp',
        'Brown Heart.webp', 'Ophiuchus.webp',
        'Cancer.webp', 'Orange Heart.webp',
        'Capricorn.webp', 'Passport Control.webp',
        'Check Box With Check.webp', 'Pisces.webp',
        'Check Mark Button.webp', 'Purple Heart.webp',
        'Check Mark.webp', 'Question Mark.webp',
        'Collision.webp', 'Red Heart.webp',
        'Cool Button.webp', 'Revolving Hearts.webp',
        'Cross Mark.webp', 'Right Anger Bubble.webp',
        'Currency Exchange.webp', 'Sagittarius.webp',
        'Customs.webp,Scorpio.webp',
        'Dizzy.webp', 'Sparkling Heart.webp',
        'Double Exclamation Mark.webp', 'Speech Balloon.webp',
        'Exclamation Mark.webp', 'Taurus.webp',
        'Exclamation Question Mark.webp', 'Thought Balloon.webp',
        'Free Button.webp', 'Top Arrow.webp',
        'Gemini.webp', 'Two Hearts.webp',
        'Green Heart.webp', 'Up Button.webp',
        'Growing Heart.webp', 'Virgo.webp',
        'Heart Decoration.webp', 'White Exclamation Mark.webp',
        'Heart Exclamation.webp', 'White Heart.webp',
        'Heart On Fire.webp', 'White Question Mark.webp',
        'Heart With Arrow.webp', 'Womens Room.webp',
        'Heart With Ribbon.webp', 'Yellow Heart.webp',
        'Hundred Points.webp', 'Zzz.webp',
        'Kiss Mark.webp'
    ],
    Objects: [
        'Abacus.webp', 'Keyboard.webp', 'Pencil.webp', 'Ballot Box With Ballot.webp', 'Key.webp',
        'Pill.webp', 'Bar Chart.webp', 'Laptop.webp', 'Printer.webp', 'Bomb.webp', 'Light Bulb.webp',
        'Purse.webp', 'Books.webp', 'Locked With Key.webp', 'Reminder Ribbon.webp',
        'Briefcase.webp', 'Luggage.webp', 'Roll Of Paper.webp',
        'Card Index Dividers.webp', 'Magnifying Glass Tilted Left.webp', 'Shopping Bags.webp',
        'Chart Decreasing.webp', 'Magnifying Glass Tilted Right.webp', 'Shopping Cart.webp',
        'Chart Increasing.webp', 'Megaphone.webp', 'Soap.webp',
        'Clapper Board.webp', 'Memo.webp', 'Sponge.webp', 'Coffin.webp',
        'Microphone.webp', 'Stethoscope.webp', 'Coin.webp', 'Microscope.webp', 'Studio Microphone.webp',
        'Crown.webp', 'Military Helmet.webp', 'Syringe.webp', 'File Folder.webp',
        'Mobile Phone.webp', 'Tear Off Calendar.webp', 'Gem Stone.webp', 'Mobile Phone With Arrow.webp',
        'Telephone Receiver.webp', 'Graduation Cap.webp', 'Money Bag.webp', 'Telephone.webp',
        'Handbag.webp', 'Money With Wings.webp', 'Telescope.webp', 'High Heeled Shoe.webp',
        'Musical Notes.webp', 'Television.webp', 'Hourglass Done.webp',
        'Musical Note.webp', 'Test Tube.webp', 'Hourglass Not Done.webp', 'Newspaper.webp',
        'Thermometer.webp', 'Identification Card.webp', 'Old Key.webp', 'Toolbox.webp',
        'Inbox Tray.webp', 'Open Book.webp', 'Top Hat.webp', 'Incoming Envelope.webp', 'Outbox Tray.webp'
    ],
    'Animals and Nature': [
        'Ant.webp', 'Evergreen Tree.webp', 'Lion.webp', 'Shrimp.webp',
        'Baby Chick.webp', 'Fire.webp', 'Llama.webp', 'Snail.webp',
        'Bat.webp', 'First Quarter Moon Face.webp', 'Lobster.webp', 'Snake.webp',
        'Bear.webp', 'First Quarter Moon.webp', 'Microbe.webp', 'Snowflake.webp',
        'Beetle.webp', 'Fish.webp', 'Monkey Face.webp', 'Snowman.webp',
        'Bird.webp', 'Flamingo.webp', 'Mosquito.webp', 'Snowman Without Snow.webp',
        'Bison.webp', 'Four Leaf Clover.webp', 'Mouse Face.webp', 'Spider.webp',
        'Black Cat.webp', 'Fox.webp', 'New Moon Face.webp', 'Spider Web.webp',
        'Blossom.webp', 'Frog.webp', 'New Moon.webp', 'Spouting Whale.webp',
        'Bouquet.webp', 'Front Facing Baby Chick.webp', 'Octopus.webp', 'Squid.webp',
        'Bug.webp', 'Full Moon Face.webp', 'Owl.webp', 'Star.webp',
        'Butterfly.webp', 'Full Moon.webp', 'Ox.webp', 'Sun Behind Cloud.webp',
        'Cactus.webp', 'Giraffe.webp', 'Palm Tree.webp', 'Sun Behind Large Cloud.webp',
        'Cat Face.webp', 'Glowing Star.webp', 'Panda.webp', 'Sun Behind Rain Cloud.webp',
        'Cat.webp', 'Gorilla.webp', 'Parrot.webp', 'Sun Behind Small Cloud.webp',
        'Cherry Blossom.webp', 'Hamster.webp', 'Paw Prints.webp', 'Sun.webp',
        'Chicken.webp', 'Hatching Chick.webp', 'Penguin.webp', 'Sun With Face.webp',
        'Cloud.webp', 'Hedgehog.webp', 'Pig Face.webp', 'Swan.webp',
        'Cloud With Lightning And Rain.webp', 'Herb.webp', 'Pig Nose.webp', 'Tiger Face.webp',
        'Cloud With Lightning.webp', 'Hibiscus.webp', 'Polar Bear.webp', 'Tiger.webp',
        'Cloud With Rain.webp', 'High Voltage.webp', 'Rabbit Face.webp', 'T Rex.webp',
        'Cloud With Snow.webp', 'Honeybee.webp', 'Rabbit.webp', 'Tropical Fish.webp',
        'Cockroach.webp', 'Horse Face.webp', 'Raccoon.webp', 'Tulip.webp',
        'Cow.webp', 'Horse.webp', 'Rainbow.webp', 'Turkey.webp',
        'Cricket.webp', 'Kangaroo.webp', 'Rosette.webp', 'Turtle.webp',
        'Deciduous Tree.webp', 'Koala.webp', 'Rose.webp', 'Unicorn.webp',
        'Deer.webp', 'Lady Beetle.webp', 'Sauropod.webp', 'Waning Crescent Moon.webp',
        'Dog Face.webp', 'Last Quarter Moon Face.webp', 'Seal.webp', 'Waxing Crescent Moon.webp',
        'Dove.webp', 'Last Quarter Moon.webp', 'Seedling.webp', 'Waxing Gibbous Moon.webp',
        'Duck.webp', 'Leopard.webp', 'Shamrock.webp', 'Zebra.webp',

    ],
    'Travel and Places': [
        'Airplane.webp', 'Beach With Umbrella.webp', 'Compass.webp', 'House.webp',
        'Motor Boat.webp', 'Roller Coaster.webp', 'Ambulance.webp', 'Camping.webp',
        'Desert Island.webp', 'Locomotive.webp', 'Police Car.webp', 'Taxi.webp',
        'Automobile.webp', 'Classical Building.webp', 'Hot Springs.webp', 'Moai.webp',
        'Rocket.webp'
    ],


}